### ISSUE TITLE
Cast id to string

### ISSUE THREAD

**Issue by bendangelo** [AliOsm/chromable#4]
https://github.com/AliOsm/chromable/blob/main/lib/chromable.rb#L106C16-L106C16

Chroma wants it cast to a string. I'm not sure how you got this working but I had to cast it.

**Comment by AliOsm** [comment]
I think the reason that I'm using UUID for the model I'm indexing. I will release a fix once I setup my new laptop.

**Comment by AliOsm** [comment]
Should be fixed in 0.3.3.

**Comment by bendangelo** [comment]
This also has to be done for chroma_embeddings and chroma_neighbors. Just search for id.

**Comment by AliOsm** [comment]
You are right, sorry for that 😅 I did the change quickly. Will handle this later today.

**Comment by AliOsm** [comment]
I will try to do it, this is my first time to setup a gem like this 😅

Would you be able to review them if I make PRs?

**Comment by bendangelo** [comment]
Yeah sure

**Comment by AliOsm** [comment]
@bendangelo it should be fixed now in 0.3.4, I hope so :3

**Comment by bendangelo** [comment]
pl
